Resources:
  Queue:
    Type: AWS::SQS::Queue
  FaceAnalysisDB:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: ImageName
          AttributeType: S
      BillingMode: PROVISIONED
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      KeySchema:
        - AttributeName: ImageName
          KeyType: HASH
      StreamSpecification:
        StreamViewType: KEYS_ONLY